tangram/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns("tangram.views",
    url("^respos/inscription/$", "inscription", name="inscription"),
    url("^respos/fiches-action/$", "fiches", name="fiches"),
    url("^respos/fiches-action/(?P<pk>\d+)/$", "fiche", name="fiche"),
    url("^respos/fiches-action/ajouter/$", "ajouter_fiche", name="ajouter_fiche"),
    url("^respos/fiches-action/(?P<pk>\d+)/modifier/$", "modifier_fiche", name="modifier_fiche"),
    url("^fichgrams/$", "fichgrams", name="fichgrams"),
    url("^fichgrams/(?P<numero>\d+)/$", "fichgram", name="fichgram"),
    url("^$", "grams", name="grams"),
)

tangram/models.py
# -*- coding:utf-8 -*-

from django.db import models
from django.contrib.auth.models import User


BRANCHE_CHOICES = (
    (1, u"Lutins"),
    (2, u"Louveteaux"),
    (3, u"Éclés"),
    (4, u"Aînés"),
)

EXPLOGRAM_CHOICES = (
    (1, u"Le pont des cultures"),
    (2, u"On est cap !"),
    (3, u"Filles/garçons"),
    (4, u"Au fil du temps"),
)


class Unite(models.Model):
    branche = models.IntegerField(u"Branche", choices=BRANCHE_CHOICES)
    nom = models.CharField(u"Nom de l'unité/équipage", max_length=100)
    inscr_explogram = models.NullBooleanField(u"Nous souhaitons participer à l'ExploGRAM")
    inscr_congram = models.NullBooleanField(u"Nous souhaitons participer au ConGRAM")
    inscr_tangram = models.NullBooleanField(u"Nous souhaitons participer au rassemblement TanGRAM")
    theme_explogram = models.CharField(max_length=100, blank=True)
    etat_explogram = models.TextField(u"Descriptif de l'ExploGRAM tel qu'il en est aujourd'hui", blank=True)
    effectif = models.PositiveIntegerField(u"Effectif approximatif", blank=True, null=True)
    contact = models.CharField(max_length=100, blank=True)
    tel = models.CharField(max_length=100, blank=True)
    user = models.OneToOneField(User)
    fg1_theme = models.IntegerField(u"Notre exploGRAM", null=True, blank=True, choices=EXPLOGRAM_CHOICES)
    fg1_projet = models.TextField(u"Le projet qu'on rêve de réaliser", blank=True)
    fg2_votants = models.CharField(u"Nombre de votants", max_length=100, blank=True)
    fg2_resultat = models.CharField(u"Résultats des votes", max_length=100, blank=True)
    fg2_elus = models.TextField(u"Sont élus", blank=True)
    fg2_adresses = models.TextField(u"Adresses", blank=True)
    fg2_propositions = models.TextField(u"Nombre de propositions à présenter", blank=True)
    fg3_date = models.CharField(u"Date", max_length=100, blank=True)
    fg3_temps = models.TextField(u"Temps consacré", blank=True)
    fg3_forme = models.TextField(u"Forme adoptée (conseil, jeux,...)", blank=True)
    fg4_theme = models.IntegerField(u"Notre exploGRAM", null=True, blank=True, choices=EXPLOGRAM_CHOICES)
    fg4_description = models.TextField(u"Le projet qu'on rêve de réaliser", blank=True)
    fg4_taches = models.BooleanField(u"Nous avons listé les tâches à faire")
    fg4_roles = models.BooleanField(u"Nous nous sommes répartis les rôles")
    fg4_partenaire = models.BooleanField(u"Nous allons chercher un partenaire")
    fg4_materiel = models.BooleanField(u"Nous avons fait la liste du matériel")
    fg4_reunions = models.IntegerField(u"Nombre de réunions de préparation", null=True, blank=True)
    fg5_theme = models.IntegerField(u"Notre exploGRAM", null=True, blank=True, choices=EXPLOGRAM_CHOICES)
    fg5_texte = models.TextField(u"La carte postale de l'exploGRAM", blank=True)
    fg5_photo = models.ImageField(u"Photo", blank=True, null=True, upload_to='carte_postale/')
    fg6_theme = models.IntegerField(u"Notre exploGRAM", null=True, blank=True, choices=EXPLOGRAM_CHOICES)
    fg6_date = models.CharField(u"Date", max_length=100, blank=True)
    fg6_descriptif = models.TextField(u"Descriptif de notre projet", blank=True)
    fg6_positifs = models.TextField(u"Les points positifs de notre projet", blank=True)
    fg7_theme = models.IntegerField(u"Notre exploGRAM", null=True, blank=True, choices=EXPLOGRAM_CHOICES)
    fg7_description = models.TextField(u"Description de notre retransmission", blank=True)
    fg7_install = models.CharField(u"Le temps qu'il nous faudra pour l'installer", max_length=100, blank=True)
    fg7_presentation = models.CharField(u"Le temps qu'il nous faudra pour le présenter pendant le rassemblement tanGRAM", max_length=100, blank=True)
    fg7_espace = models.CharField(u"L'espace qu'il nous faudra", max_length=100, blank=True)
    fg7_micro = models.BooleanField(u"Nous aurons besoin d'un micro")
    fg7_ecran = models.BooleanField(u"Nous aurons besoin d'un écran")
    fg7_expo = models.BooleanField(u"Nous aurons besoin de supports expo")
    fg7_autre = models.TextField(u"Nous aurons besoin d'autres choses", blank=True)
    fg1_ok = models.BooleanField(u"Gram attribué")
    fg2_ok = models.BooleanField(u"Gram attribué")
    fg3_ok = models.BooleanField(u"Gram attribué")
    fg4_ok = models.BooleanField(u"Gram attribué")
    fg5_ok = models.BooleanField(u"Gram attribué")
    fg6_ok = models.BooleanField(u"Gram attribué")
    fg7_ok = models.BooleanField(u"Gram attribué")
    nb_grams = models.IntegerField(u"nombre de grams", default=0)

    def save(self, *args, **kwargs):
        self.nb_grams = sum([int(getattr(self, 'fg%u_ok' % i)) for i in range(1, 8)])
        super(Unite, self).save(*args, **kwargs)


class FicheAction(models.Model):
    titre = models.CharField(u"Titre", max_length=100)
    par = models.CharField(u"Action réalisée par", max_length=100, blank=True)
    public = models.TextField(u"Description public (âge, autonomie, effectif…)", blank=True)
    deroule = models.TextField(u"Descriptif du déroulé", blank=True)
    activite = models.CharField(u"Type d'activité (grand jeux, forum, projet de longue durée…)", max_length=100, blank=True)
    objectifs = models.TextField(u"Objectifs", blank=True)
    place = models.TextField(u"Place dans une démarche d'année (lancement, construction, conclusion…)", blank=True)
    duree = models.CharField(u"Durée", max_length=100, blank=True)
    lancement = models.TextField(u"Place dans les respos dans le lancement", blank=True)
    realisation = models.TextField(u"Place dans les respos dans la réalisation", blank=True)
    valorisation = models.TextField(u"Place dans les respos dans la valorisation", blank=True)
    biblio = models.TextField(u"Bibliographie", blank=True)
    partenaires = models.TextField(u"Les partenaires (si c'est le cas)", blank=True)
    matos = models.TextField(u"Besoins matériels", blank=True)
    annexe = models.FileField(u"Annexes jointes", blank=True, upload_to='fiche_action')
    user = models.ForeignKey(User)

    def __unicode__(self):
        return self.titre

tangram/templates/tangram/ficheaction_detail.html
{% extends "base.html" %}
{% load mezzanine_tags %}

{% block main %}

<h4>{{ ficheaction.titre }}</h4>
{% if ficheaction.par %}<p><strong>Action réalisée par</strong></strong> : <br>{{ ficheaction.par }}</p>{% endif %}
{% if ficheaction.public %}<p><strong>Description public (âge, autonomie, effectif…)</strong> : <br>{{ ficheaction.public }}</p>{% endif %}
{% if ficheaction.deroule %}<p><strong>Descriptif du déroulé</strong> : <br>{{ ficheaction.deroule }}</p>{% endif %}
{% if ficheaction.activite %}<p><strong>Type d'activité (grand jeux, forum, projet de longue durée…)</strong> : <br>{{ ficheaction.activite }}</p>{% endif %}
{% if ficheaction.objectifs %}<p><strong>Objectifs</strong> : <br>{{ ficheaction.objectifs }}</p>{% endif %}
{% if ficheaction.place %}<p><strong>Place dans une démarche d'année (lancement, construction, conclusion…)</strong> : <br>{{ ficheaction.place }}</p>{% endif %}
{% if ficheaction.duree %}<p><strong>Durée</strong> : <br>{{ ficheaction.duree }}</p>{% endif %}
{% if ficheaction.lancement %}<p><strong>Place dans les respos dans le lancement</strong> : <br>{{ ficheaction.lancement }}</p>{% endif %}
{% if ficheaction.realisation %}<p><strong>Place dans les respos dans la réalisation</strong> : <br>{{ ficheaction.realisation }}</p>{% endif %}
{% if ficheaction.valorisation %}<p><strong>Place dans les respos dans la valorisation</strong> : <br>{{ ficheaction.valorisation }}</p>{% endif %}
{% if ficheaction.biblio %}<p><strong>Bibliographie</strong> : <br>{{ ficheaction.biblio }}</p>{% endif %}
{% if ficheaction.partenaires %}<p><strong>Les partenaires (si c'est le cas)</strong> : <br>{{ ficheaction.partenaires }}</p>{% endif %}
{% if ficheaction.matos %}<p><strong>Besoins matériels</strong> : <br>{{ ficheaction.matos }}</p>{% endif %}
{% if ficheaction.annexe %}<p><strong>Annexes jointes</strong> : <br>{{ ficheaction.annexe }}</p>{% endif %}

{% if ficheaction.user == request.user %}
    <a href="{% url 'modifier_fiche' ficheaction.pk %}" class="btn btn-default">Modifier</a>
{% endif %}

{% endblock %}

tangram/templates/tangram/ficheaction_form.html
{% extends "base.html" %}

{% block main %}

{% if request.user.is_authenticated %}

    <form method="POST" action="#">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Enregister</button>
    </form>

{% else %}

    <p>Il faut d'abord te <a href="{% url "login" %}?next={{ request.path }}">connecter</a> avant de pouvoir remplir une fiche action.</p>

{% endif %}

{% endblock %}

tangram/templates/tangram/ficheaction_list.html
{% extends "base.html" %}
{% load mezzanine_tags %}

{% block main %}

{% editable page.richtextpage.content %}
    {{ page.richtextpage.content|richtext_filters|safe }}
{% endeditable %}

<ul>
{% for fiche in object_list %}
    <li><a href="{% url 'fiche' fiche.pk %}">{{ fiche }}</a></li>
{% endfor %}
</ul>

<a href="{% url 'ajouter_fiche' %}" class="btn btn-default">Ajouter une fiche action</a>

{% endblock %}

tangram/templates/tangram/fichgram.html
{% extends "base.html" %}

{% block main %}

<form method="POST" enctype="multipart/form-data" method="post" action="#">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Enregister</button>
</form>

{% endblock %}

tangram/templates/tangram/fichgrams.html
{% extends "base.html" %}
{% load mezzanine_tags %}

{% block main %}

{% if not request.user.is_authenticated %}
    <p>Il faut d'abord te <a href="{% url "login" %}?next={{ request.path }}">connecter</a> avant de pouvoir remplir tes FichGRAMs.</p>
{% endif %}

{% if not unite %}
    <p>Il faut d'abord t'<a href="/respos/inscription/?next={{ request.path }}">inscrire</a> avant de pouvoir remplir tes FichGRAMs.</p>
{% endif %}

{% if request.user.is_authenticated and unite %}
    {% editable page.richtextpage.content %}
        {{ page.richtextpage.content|richtext_filters|safe }}
    {% endeditable %}
    <ol>
        <li><a href="/fichgrams/1/">Choix</a>{% if unite.fg1_ok %} (gram attribué){% endif %}</li>
        <li><a href="/fichgrams/2/">&Eacute;lection</a>{% if unite.fg2_ok %} (gram attribué){% endif %}</li>
        <li><a href="/fichgrams/3/">Restitution</a>{% if unite.fg3_ok %} (gram attribué){% endif %}</li>
        <li><a href="/fichgrams/4/">Pr&eacute;paration</a>{% if unite.fg4_ok %} (gram attribué){% endif %}</li>
        <li><a href="/fichgrams/5/">R&eacute;alisation</a>{% if unite.fg5_ok %} (gram attribué){% endif %}</li>
        <li><a href="/fichgrams/6/">Bilan</a>{% if unite.fg6_ok %} (gram attribué){% endif %}</li>
        <li><a href="/fichgrams/7/">Retransmission</a>{% if unite.fg7_ok %} (gram attribué){% endif %}</li>
    </ol>
{% endif %}

{% endblock %}

tangram/templates/tangram/grams.html
{% extends "base.html" %}
{% load mezzanine_tags %}

{% block main %}

{% editable page.richtextpage.content %}
    {{ page.richtextpage.content|richtext_filters|safe }}
{% endeditable %}

<ul>
{% for unite in unites %}
    <li>{{ unite.nom }} ({{ unite.get_branche_display }})&nbsp;: {{ unite.nb_grams }} gram{{ unite.nb_grams|pluralize }}</li>
{% endfor %}
</ul>

{% endblock %}

tangram/templates/tangram/inscription.html
{% extends "base.html" %}

{% block main %}

<form method="POST" action="#">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Enregister</button>
</form>

{% endblock %}